force-app/main/default/objects/Anken__c/Anken__c.object-meta.xml
<CustomObject>
    <label>案件</label>
    <nameField>
        <label>案件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Anken__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>案件</relationshipLabel>
    <relationshipName>Account_rel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先責任者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>案件</relationshipLabel>
    <relationshipName>Contact_rel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>終了期日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <label>進捗</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>開始期日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状況</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>新規</fullName>
                <default>true</default>
                <label>新規</label>
            </value>
            <value>
                <fullName>進行中</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
            <value>
                <fullName>レビュー待ち</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>タスク</label>
    <nameField>
        <label>タスク名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Anken__c.field-meta.xml
<CustomField>
    <fullName>Anken__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>案件</label>
    <referenceTo>Anken__c</referenceTo>
    <relationshipLabel>タスク</relationshipLabel>
    <relationshipName>Anken_rel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ParentTask__c.field-meta.xml
<CustomField>
    <fullName>ParentTask__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>親タスク</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipLabel>タスク</relationshipLabel>
    <relationshipName>ParentTask_rel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/PlanEndDate__c.field-meta.xml
<CustomField>
    <fullName>PlanEndDate__c</fullName>
    <label>予定終了期日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/PlanStartDate__c.field-meta.xml
<CustomField>
    <fullName>PlanStartDate__c</fullName>
    <label>予定開始期日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>優先度</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>高</fullName>
            </value>
            <value>
                <fullName>中</fullName>
            </value>
            <value>
                <fullName>低</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <defaultValue>0</defaultValue>
    <label>進捗</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>未着手</fullName>
                <default>true</default>
                <label>未着手</label>
            </value>
            <value>
                <fullName>進行中</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
            <value>
                <fullName>レビュー待ち</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskTriggerHandlerTest.cls
@isTest
public with sharing class TaskTriggerHandlerTest {

    @TestSetup
    static void setUp(){
        Account insAccount = new Account();
        Contact insContact = new Contact();
        Anken__c insAnken = new Anken__c();

        insAccount.Name = 'テスト取引先';
        insContact.FirstName = 'テスト';
        insContact.LastName = '責任者';
        insAnken.Name = 'テスト案件';
        insAnken.Account__c = insAccount.Id;
        insAnken.Contact__c = insContact.Id;
        insAnken.StartDate__c = Date.today();
        insAnken.EndDate__c = Date.today()+7;
        insAnken.Status__c = '新規';

        insert insAccount;
        insert insContact;
        insert insAnken;
    }

    /*
    * testMethod01
    * タスク作成
    * @param: 無し
    * @return: 無し
    */
    static testMethod void testMethod01(){

        Task__c insParentTask = new Task__c();

        //親タスク
        insParentTask = createTask(null,true);

        insParentTask.Progress__c = 50;
        update insParentTask;
        System.assertEquals(50, insParentTask.Progress__c);
        insParentTask.Progress__c = 80;
        update insParentTask;
        System.assertEquals(80, insParentTask.Progress__c);
        insParentTask.Progress__c = 100;
        update insParentTask;
        System.assertEquals(100, insParentTask.Progress__c);
    }

    /*
    * testMethod02
    * 親タスク更新
    * @param: 無し
    * @return: 無し
    */
    @isTest
    static void testMethod02(){
        
        Task__c insParentTask1 = new Task__c();
        Task__c insParentTask2 = new Task__c();
        Task__c insChildTask1 = new Task__c();
        Task__c insChildTask2 = new Task__c();
        List<Task__c> taskList = new List<Task__c>();
        List<Task__c> updateTaskList = new List<Task__c>();

        insParentTask1 = createTask(null,true);
        insParentTask2 = createTask(null,false);
        insParentTask2.Name = 'テストタスク２';
        insert insParentTask2;

        insChildTask1 = createTask(insParentTask1.id,false);
        insChildTask1.Name = 'テスト子タスク１';
        insert insChildTask1;
        insChildTask2 = createTask(insParentTask2.id,false);
        insChildTask2.Name = 'テスト子タスク２';
        insert insChildTask2;

        insParentTask1.Progress__c = 100;
        insParentTask1.Status__c = '完了';
        insParentTask2.Progress__c = 100;
        insParentTask2.Status__c = '完了';

        updateTaskList.add(insParentTask1);
        updateTaskList.add(insParentTask2);

        update updateTaskList;
        
        taskList = [SELECT id,Progress__c,Status__c FROM Task__c WHERE id = :updateTaskList];
        System.debug(taskList);

        for(Task__c task : taskList){
            //進捗
            System.assertEquals(100, task.Progress__c);
            //状況
            System.assertEquals('完了', task.Status__c);
        }
    }

    /*
    * testMethod03
    * 子タスク更新
    * @param: 無し
    * @return: 無し
    */
    @isTest
    static void testMethod03(){

        Task__c insParentTask1 = new Task__c();
        Task__c insParentTask2 = new Task__c();
        Task__c insChildTask1 = new Task__c();
        Task__c insChildTask2 = new Task__c();
        Task__c insChildTask3 = new Task__c();
        Task__c insChildTask4 = new Task__c();
        List<Task__c> taskList = new List<Task__c>();
        List<Task__c> updateTaskList = new List<Task__c>();

        insParentTask1 = createTask(null,true);
        insParentTask2 = createTask(null,false);
        insParentTask2.Name = 'テストタスク２';
        insert insParentTask2;

        insChildTask1 = createTask(insParentTask1.id,false);
        insChildTask1.Name = 'テスト子タスク１';
        insert insChildTask1;
        insChildTask2 = createTask(insParentTask2.id,false);
        insChildTask2.Name = 'テスト子タスク２';
        insert insChildTask2;
        insChildTask3 = createTask(insParentTask1.id,false);
        insChildTask3.Name = 'テスト子タスク３';
        insChildTask3.Progress__c = 100;
        insChildTask3.Status__c = '完了';
        insert insChildTask3;
        insChildTask4 = createTask(insParentTask2.id,false);
        insChildTask4.Name = 'テスト子タスク４';
        insChildTask4.Progress__c = 100;
        insChildTask4.Status__c = '完了';
        insert insChildTask4;

        insChildTask1.Progress__c = 100;
        insChildTask1.Status__c = '完了';
        insChildTask2.Progress__c = 100;
        insChildTask2.Status__c = '完了';

        updateTaskList.add(insChildTask1);
        updateTaskList.add(insChildTask2);

        update updateTaskList;
        
        taskList = [SELECT id,Progress__c,Status__c FROM Task__c WHERE id = :updateTaskList];
        System.debug(taskList);

        for(Task__c task : taskList){
            //進捗
            System.assertEquals(100, task.Progress__c);
            //状況
            System.assertEquals('完了', task.Status__c);
        }
    }

    /*
    * createTask
    * タスクレコード作成
    * @param:parentTaskId　親タスクレコードID
    * @param:insFlg　insert実行フラグ(False:実行しない、True:実行)
    * @return:タスクレコード 
    */
    static Task__c createTask(Id parentTaskId, Boolean insFlg){

        Task__c insTask = new Task__c();

        insTask.Name = 'テストタスク';
        insTask.PlanStartDate__c = date.today();
        insTask.PlanEndDate__c = date.today()+7;
        insTask.Priority__c = '低';
        insTask.Progress__c = 0;
        insTask.Status__c = '未着手';
        if(!String.isEmpty(parentTaskId)){
            insTask.ParentTask__c = parentTaskId;
        }
        if(insFlg)insert insTask;
        return insTask;
    }
}