force-app/main/default/objects/test__c/test__c.object-meta.xml
<CustomObject>
    <label>test</label>
    <nameField>
        <displayFormat>aｂ-{000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/test__c/fields/SumCurrency__c.field-meta.xml
<CustomField>
    <fullName>SumCurrency__c</fullName>
    <formula>currency1__c  +  currency2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SumCurrency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/test__c/fields/test__c.field-meta.xml
<CustomField>
    <fullName>test__c</fullName>
    <label>test</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>test</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OperationTriggerHandler.cls
public class OperationTriggerHandler {
    /*@future
    public static void OperationTest() {
        //throw new NullPointerException();
        wait(10000);
        
    }
    
    public static void wait(Integer ms){
        

        Long startTime = DateTime.now().getTime();
        Long finishTime = DateTime.now().getTime();
    
        

        while((finishTime - startTime) < ms){
            finishTime = DateTime.now().getTime();
        }

        throw new NullPointerException();
    }*/

    public static void beforeupdate(){
        System.debug('beforeupdate1');
        test__c test = [SELECT id,SumCurrency__c FROM test__c WHERE id = 'a02J3000003INzOIAW'];
        System.debug(test.SumCurrency__c);
    }
}